name = "todoserverlessbackend"
main = "src/index.ts"
compatibility_date = "2024-11-23"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTg5NGU1ODYtN2U1My00ZjRiLWE1NDQtNmEzODNiY2I2ODBkIiwidGVuYW50X2lkIjoiZDIwYzk1NGU2MGU1YzkxYmZmNTdlY2FlNDVlYjEzNTU1NTFmNGRiMzBiMWM1N2QxMTcxMGYyOTBjNmJjNDlmMyIsImludGVybmFsX3NlY3JldCI6IjBhMDNiNmU4LTIwM2UtNGFjMi1hMTM4LWJmYWJiOGIzNmIzNSJ9.TzQjx4wpRpWiB_f9QXrmUZDlVq6sz6xeCuC4ZjUd4Cg"
JWT_SECRET="nagmani"
